/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppDeliveryRouteImport } from './routes/_app/delivery'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCateringRouteImport } from './routes/_app/catering'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders.$id'
import { Route as ApiPublicWebhooksChannelRouteImport } from './routes/api/public/webhooks.$channel'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRoute = AppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCateringRoute = AppCateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)
const ApiPublicWebhooksChannelRoute =
  ApiPublicWebhooksChannelRouteImport.update({
    id: '/api/public/webhooks/$channel',
    path: '/api/public/webhooks/$channel',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/analytics': typeof AppAnalyticsRoute
  '/catering': typeof AppCateringRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/delivery': typeof AppDeliveryRoute
  '/integrations': typeof AppIntegrationsRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/menu': typeof AppMenuRoute
  '/messages': typeof AppMessagesRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/payments': typeof AppPaymentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/system': typeof AppSystemRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/api/public/webhooks/$channel': typeof ApiPublicWebhooksChannelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/analytics': typeof AppAnalyticsRoute
  '/catering': typeof AppCateringRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/delivery': typeof AppDeliveryRoute
  '/integrations': typeof AppIntegrationsRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/menu': typeof AppMenuRoute
  '/messages': typeof AppMessagesRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/payments': typeof AppPaymentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/system': typeof AppSystemRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/api/public/webhooks/$channel': typeof ApiPublicWebhooksChannelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/catering': typeof AppCateringRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/delivery': typeof AppDeliveryRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/orders': typeof AppOrdersRouteWithChildren
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/api/public/webhooks/$channel': typeof ApiPublicWebhooksChannelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/analytics'
    | '/catering'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/integrations'
    | '/inventory'
    | '/locations'
    | '/menu'
    | '/messages'
    | '/orders'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/system'
    | '/orders/$id'
    | '/api/public/webhooks/$channel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/access'
    | '/analytics'
    | '/catering'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/integrations'
    | '/inventory'
    | '/locations'
    | '/menu'
    | '/messages'
    | '/orders'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/system'
    | '/orders/$id'
    | '/api/public/webhooks/$channel'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/access'
    | '/_app/analytics'
    | '/_app/catering'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/delivery'
    | '/_app/integrations'
    | '/_app/inventory'
    | '/_app/locations'
    | '/_app/menu'
    | '/_app/messages'
    | '/_app/orders'
    | '/_app/payments'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/system'
    | '/_app/orders/$id'
    | '/api/public/webhooks/$channel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicWebhooksChannelRoute: typeof ApiPublicWebhooksChannelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delivery': {
      id: '/_app/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AppDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catering': {
      id: '/_app/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof AppCateringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/api/public/webhooks/$channel': {
      id: '/api/public/webhooks/$channel'
      path: '/api/public/webhooks/$channel'
      fullPath: '/api/public/webhooks/$channel'
      preLoaderRoute: typeof ApiPublicWebhooksChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCateringRoute: typeof AppCateringRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveryRoute: typeof AppDeliveryRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppMenuRoute: typeof AppMenuRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppSystemRoute: typeof AppSystemRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCateringRoute: AppCateringRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveryRoute: AppDeliveryRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppMenuRoute: AppMenuRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppSystemRoute: AppSystemRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicWebhooksChannelRoute: ApiPublicWebhooksChannelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
