// Version bumper — single source of truth is the root VERSION file.
// Scheme: 0.0.0 → +1 per push; digits carry at 10 (0.0.9 → 0.1.0, 0.9.9 → 1.0.0).
// Usage:  node scripts/bump-version.mjs        (bump + sync everywhere)
//         node scripts/bump-version.mjs --set 0.2.0
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const VERSION_FILE = resolve(root, "VERSION");

function bump(v) {
  let [maj, min, pat] = v.trim().split(".").map(Number);
  pat += 1;
  if (pat >= 10) { pat = 0; min += 1; }
  if (min >= 10) { min = 0; maj += 1; }
  return `${maj}.${min}.${pat}`;
}

const setIdx = process.argv.indexOf("--set");
const current = readFileSync(VERSION_FILE, "utf8").trim();
const next = setIdx > -1 ? process.argv[setIdx + 1] : bump(current);

writeFileSync(VERSION_FILE, next + "\n");

// App-side constants (imported by UI footers)
const banner = `// Auto-generated by scripts/bump-version.mjs — do not edit by hand.\nexport const APP_VERSION = "${next}";\n`;
for (const p of ["website/src/version.ts", "dine-central-hub/src/version.ts"]) {
  writeFileSync(resolve(root, p), banner);
}

// Keep package.json versions in sync
for (const p of ["website/package.json", "dine-central-hub/package.json"]) {
  const file = resolve(root, p);
  const pkg = JSON.parse(readFileSync(file, "utf8"));
  pkg.version = next;
  writeFileSync(file, JSON.stringify(pkg, null, 2) + "\n");
}

console.log(`version: ${current} -> ${next}`);
